#!/bin/bash

ROLE="$1"

if [ -z "$ROLE" ]
then
    echo "Please specify the name of the new role as first parameter." 2>&1
    exit 0
fi

git submodule add "https://github.com/debops/ansible-${ROLE}.git" docs/ansible/roles

./patch_gitmodules
