#!/bin/bash
## @author Copyright (C) 2016 Robin Schneider <ypid@riseup.net>
## @license GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.html>

## Link the global.rst include file into all parts of DebOps which use it.
## Support global link definitions.
## https://github.com/debops/docs/issues/155

set -e

test -f "includes/global.rst" || exit 1

DOCS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

find . -type d -iwholename '.*docs/includes' | while read -r target_include_dir
do
    pushd "$target_include_dir" 1>/dev/null
    pwd
    ## ln: invalid option -- 'r'
    ## The version of ln on Travis does not have --relative :<
    ln -sf "$DOCS_DIR/includes/global.rst" global.rst

    ## Should not be needed but for some reason when setting up DebOps Contrib,
    ## it was needed for CHANGES.rst.
    ln -sf "$DOCS_DIR/includes" ../../

    popd 1>/dev/null
    ## Print for debugging for now.
done

test -d ansible/roles && ln -sf ../../includes/ ansible/roles

## Seems that this hack is needed for Travis CI. Not sure why. For readthedocs.org it is not needed.
test -d debops-api && ln -sf docs/includes debops-api/
test -d debops-keyring && ln -sf docs/includes debops-keyring/
test -d debops-policy && ln -sf docs/includes debops-policy/
