#!/bin/bash
## @author Copyright (C) 2016 Robin Schneider <ypid@riseup.net>
## @license GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.html>

## Run hook scripts just before Sphinx runs.
## Hook is installed from `conf.py` from Sphinx.

_bin/linkincludes
_bin/prepare_repos_before_sphinx_runs
